### ISSUE TITLE
Is it possible to use the samplers by themselves?

### ISSUE THREAD

**Issue by gtsambos** [mertensu/ABrox#1]
Hello, thank you for the excellent and well-documented software 😃 This is not an 'issue', just a question.

I wish to do an ABC-based inference using ABC-MCMC, and can see that you have provided a template for this. For a few reasons, I want to run my simulations and extract summary statistics outside of ABrox, but do the ABC-MCMC sampling + parameter estimation with ABrox.

Is there some way I can do this, either within the GUI or by modifying one of the Python project scripts that the GUI creates?

**Comment by mertensu** [comment]
Hi Georgia,

thanks for your interest in ABrox! 

Sure, this is possible. When you create a Python script either from scratch or by using the GUI to generate it for you (which I would recommend), there is a key 'reftable' with an option to specify an external reference table ('extref'). The default is null but you can provide a path to the reference table. Also, you might take a look at the corresponding paper [link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0193981) There, it says:

> ABrox usually generates the reference table internally but it also possible to import an external reference table stored in a comma separated value (csv) file. The header of csv-file needs to satisfy the the following conditions. There has to be a column named idx containing the model index. Furthermore, if there are k summary statistics, each value has to be stored in separate columns named s_ followed by a number (usually 1 to k). The same logic applies to the parameters where each parameter column name should start with p_. In addition to the columns containing information about summary statistics and parameter prior distributions, there has to be a column named distance containing the distance to the observed summary statistics.

While it is totally fine to use the ABC-MCMC approach, I would still like to inform you about some recent progress in ABC from our lab (see e.g. [here](https://onlinelibrary.wiley.com/doi/abs/10.1111/bmsp.12159). If you are interested in applying a similar technique as described in the paper (which even gives you the full posterior distribution of each parameter), please let me know. 

Best,
Ulf

**Comment by gtsambos** [comment]
Oh awesome, that's great news! Thanks for this helpful response - I'll try this out in the next few days.

> While it is totally fine to use the ABC-MCMC approach, I would still like to inform you about some recent progress in ABC from our lab (see e.g. here. If you are interested in applying a similar technique as described in the paper (which even gives you the full posterior distribution of each parameter), please let me know.

Thanks very much for letting me know! I'm quite new to ABC and still have a lot to learn - I think I will try to get to grips with ABC-MCMC first just because it seems to be the standard approach in my area (demographic inference based on genetic datasets). Once I have a better sense of what the strengths and weaknesses of this approach are, I may get back in touch about this alternative method.
